version: '3.9'

services:
  front:
    container_name: front-project
    build: 
      dockerfile: Dockerfile
      context: './front-project'
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_URL=http://api:3000
    depends_on:
      - api
      - db

  api:
    container_name: api-project
    build: 
      dockerfile: Dockerfile
      context: './api-project'
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgresgg
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: >
      bash -c "npx wait-on tcp:db:5432 && npm run typeorm migration:run && npm start"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pgdata: {}