version: '3.9'

services:
  front:
    container_name: front-project
    build: 
      dockerfile: Dockerfile
      context: './front-project'
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_URL=http://api:3000
    depends_on:
      - api

  api:
    container_name: api-project
    build: 
      dockerfile: Dockerfile
      context: './api-project'
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgresgg
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}